load("@rules_go//go:def.bzl", "go_library")

go_library(
    name = "datasets",
    srcs = [
        "root.go",
    ],
    importpath = "datasets_cli/v2/datasets",
    visibility = ["//visibility:public"],
    deps = [
        "//go/util",
        "//go/util/command",
        "@com_github_gosuri_uiprogress//:uiprogress",
    ],
)
