name: Build and Test
on:
  push:
  pull_request:
  workflow_dispatch:
defaults:
  run:
    working-directory: ./client
jobs:
  build-and-test:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os:
          - ubuntu-latest
          - ubuntu-24.04-arm
          - macos-latest # arm64
          - macos-13 # osx-64
          - windows-latest
          - windows-11-arm
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        #   - name: Set up Go
        #     uses: actions/setup-go@v5
        #     with:
        #       go-version: '1.21' # Adjust version as needed
        #   - name: Install Bazelisk
        #     run: |
        #       curl -LO "https://github.com/bazelbuild/bazelisk/releases/latest/download/bazelisk-linux-amd64"
        #       chmod +x bazelisk-linux-amd64
        #       sudo mv bazelisk-linux-amd64 /usr/local/bin/bazel
      - uses: bazel-contrib/setup-bazel@0.15.0
        with:
          bazelisk-cache: true
          disk-cache: ${{ github.workflow }}
          repository-cache: true
      - name: Add workdir to PATH
        run: |
          echo "$(pwd)" >> $GITHUB_PATH
      - name: Build
        run: bazel build apps/public/Datasets/...
      - name: Smoke test
        run: |
          ./bazel-bin/apps/public/Datasets/v2/cmd/datasets/datasets_/datasets
          ./bazel-bin/apps/public/Datasets/v2/cmd/datasets/datasets_/datasets \
            download virus genome taxon 101947
      - name: Upload build artifacts
        uses: actions/upload-artifact@v4
        if: success()
        with:
          name: datasets-binary
          path: client/bazel-bin/apps/public/Datasets/v2/cmd/datasets/datasets_/datasets
